### ISSUE TITLE
Decide on e-mail strategy

### ISSUE THREAD

**Issue by mikehern** [codeforamerica/syracuse_biz_portal#137]

**Comment by racheledelman** [comment]
@mikehern was this just related to accounts, or do you recall anything else that involved emails?

**Comment by mikehern** [comment]
@racheledelman this was just specific to registering and logging in for an account, during the Jan 3 build.  The issue is moot since we don't have native user accounts anymore.  Appreciate the follow-up!  Closing the issue.
