### ISSUE TITLE
Add content to footer

### ISSUE THREAD

**Issue by mikehern** [codeforamerica/syracuse_biz_portal#140]

**Comment by adamewood** [comment]
Left column:

Plan
Launch
Grow

Center column:

Division of Business Development
City Hall Commons, 7th Floor
201 E. Washington St. – Syracuse, NY 13202
(315) 473-3275

Right column: 

Resource matching  (link)
Permit tracker (link)

**Comment by racheledelman** [comment]
Can we get the correct contract info in here?

Currently:
![image](https://cloud.githubusercontent.com/assets/2693690/22613521/d6e61e92-ea2d-11e6-87cb-a0862368ad67.png)

**Comment by adamewood** [comment]
City Hall Commons, 7th Floor
201 E. Washington St.
Syracuse, NY 13202
