### ISSUE TITLE
Content for "Popular Pages" section

### ISSUE THREAD

**Issue by mikehern** [codeforamerica/syracuse_biz_portal#141]

**Comment by adamewood** [comment]
Link to:

Forms and Applications
http://www.syracuse.ny.us/Documents_and_Forms.aspx#2
List of Permitted Home-based Business http://www.syrgov.net/Home_Occupation_Questions.aspx
Business License Information http://www.syrgov.net/Documents_and_Forms.aspx#Finance

**Comment by cweems** [comment]
Right now the popular pages are defined by a page picker in the admin interface, and there isn't an easy way to make that page picker accommodate external links as far as I know. @millzpaugh @glassresistor do you know if there's an easy way to accomplish this in wagtail? Going to suggest for now that we just choose popular pages internal to our site.

**Comment by cweems** [comment]
Added these to the cms in production.
