### ISSUE TITLE
IPS Progress email

### ISSUE THREAD

**Issue by adamewood** [codeforamerica/syracuse_biz_portal#147]

**Comment by adamewood** [comment]
-Look at available data and decide what to include
-write copy

**Comment by adamewood** [comment]
Existing: 
Dept approval date
Approval Status
Permit Application No
Permit App type
Status
Description of work
Comments

**Comment by adamewood** [comment]
@millzpaugh Do we still need to worry about this or can we close this because of the # of emails they already have in IPS?

**Comment by millzpaugh** [comment]
yes, we can close this
