### ISSUE TITLE
Add dynamic icons to homepage

### ISSUE THREAD

**Issue by racheledelman** [codeforamerica/syracuse_biz_portal#2]
Find Noun Project icons that correspond to existing "step pages". Upload for each page and render on homepage. (****We need to setup a place for media files before we can do this - Heroku dynos don't support file uploads.)

**Comment by racheledelman** [comment]
@millzpaugh is this the same as #3? And are media files still an issue, or can I upload them to Wagtail?

**Comment by millzpaugh** [comment]
#3 are the icons associated with resource types (phone number, url, email, etc...) on all step pages. This issue refers to icons associated with a header on a step page.

**Comment by millzpaugh** [comment]
also I'd check in with @glassresistor about whether or the file uploads are ready.
