### ISSUE TITLE
Deal with IPS API rate limiting our server

### ISSUE THREAD

**Issue by cweems** [codeforamerica/syracuse_biz_portal#224]

**Comment by glassresistor** [comment]
Just saw this and would advise against it for a couple of reasons.  Mainly that caching is hard and your likely to cache things you don't mean to or keep stale data around.  If theres a really specific reason for it maybe but if its just an optimization I'd advise against it.

**Comment by cweems** [comment]
There's a pretty compelling reason: we've apparently brought down the API just by testing. Wouldn't want actual users to experience that kind of outage.

**Comment by millzpaugh** [comment]
I agree - it breaks almost every time I'm developing with it (I estimate about ~20 pings/minute causes it to go down for 10 minutes). I've used the Django request cache before and it's worked well - https://docs.djangoproject.com/en/1.7/topics/cache/

**Comment by glassresistor** [comment]
So caching will not help us.  We need them to turn off rate limiting for requests from our domain(or add a password to the api) or we have to make our requests rate limit themselves.  The later will cause apparent downtime and is not advised.
