### ISSUE TITLE
Certificate of Use status bar colors and icons

### ISSUE THREAD

**Issue by racheledelman** [codeforamerica/syracuse_biz_portal#226]
Let's apply these colors and icons to the CU inspection status bars:
- Pass: #B5E3BD `fa-check-circle-o`
- Fail: #E8B5B5, we can either user `fa-exclamation-circle` (an exclamation mark that is more of a "warning, take action!" message(, or `fa-ban` (which is a more neutral "this did not pass" message). What do you think is most appropriate? 
- N/A: #D7D7D7 (for now), none
- In Progress: #B8D9FF `fa-refresh`
- No Progress: #D7D7D7 (for now), none
- No Work Started: #D7D7D7 (for now) `fa-clock-o`

![image](https://cloud.githubusercontent.com/assets/2693690/22539394/af2743aa-e8ce-11e6-9a92-54123840d6c6.png)

**Comment by millzpaugh** [comment]
Great - thanks Rachel!
