### ISSUE TITLE
Clarify permit tracker error message

### ISSUE THREAD

**Issue by racheledelman** [codeforamerica/syracuse_biz_portal#239]
Un-acronym NBD and add contact information. Can you find this, @adamewood?

![image](https://cloud.githubusercontent.com/assets/2693690/22850123/991e25dc-efb9-11e6-80f4-068a120b3ae8.png)

**Comment by adamewood** [comment]
ROW permits 
Youlanda Johnson, Zoning Permit Coordinator
Phone: (315) 448-4714
yjohnson@syrgov.net

Building permits
Central Permit Office
(315) 448-8600
DOCEPermits@syrgov.net

Business Licenses
Pam Dalton, Business Licensing Coordinator
Phone: (315) 448-8474 
Email: BusinessLicense@SyrGov.net

**Comment by racheledelman** [comment]
@adamewood since these will be hardcoded, I'd rather avoid listing specific people, since they might leave. Building permits looks good, but is there a generic office phone and email we can use for ROW and Business Licenses?

**Comment by adamewood** [comment]
You can use the information to hard code  for all of those except youlanda's (ROW). I'll ask Sam White about it.

**Comment by racheledelman** [comment]
@millzpaugh, can you change the errors to the following?

![license error](https://cloud.githubusercontent.com/assets/2693690/22995799/2bd80d96-f381-11e6-9231-46ce44cb4609.png)

![permit error](https://cloud.githubusercontent.com/assets/2693690/22995800/2bdf83f0-f381-11e6-9ec9-f9111917a5aa.png)

Details:
**ROW permits**
Zoning Permit Coordinator
Phone: (315) 448-4715
CentralPermitOffice@syrgov.net

**Building permits**
Central Permit Office
(315) 448-8600
DOCEPermits@syrgov.net

**Business Licenses**
Business Licensing Coordinator
Phone: (315) 448-8474
Email: BusinessLicense@SyrGov.net
