### ISSUE TITLE
Add next step info for permit and licenses we can't search

### ISSUE THREAD

**Issue by racheledelman** [codeforamerica/syracuse_biz_portal#240]
Let's add a sentence to the permit/license search pages about what you can do if you want to look up something we don't support. Who should they contact? Can we add a phone number/email?

Also welcome ideas for nicer ways to say "you can't do this".

![image](https://cloud.githubusercontent.com/assets/2693690/22850180/4d329486-efba-11e6-9895-9c03d7e79458.png)

![image](https://cloud.githubusercontent.com/assets/2693690/22850182/5781a9c2-efba-11e6-8594-e312e67fe252.png)

**Comment by adamewood** [comment]
I will ask Sam and the team, but I think you can just call the CPO, so we can add contact info for that. Well spotted, I agree we need something "nicer".

**Comment by racheledelman** [comment]
`Can't find what you're looking for? Give the Central Permit Office a call`
 and then put Pam's info on CoU and youlanda's on ROW
