### ISSUE TITLE
Change CofU case sensitivity

### ISSUE THREAD

**Issue by adamewood** [codeforamerica/syracuse_biz_portal#248]
Please change the input box for certificate of use to not be case sensitive.

OR

Since every CU starts with "CU20", we could hardcode that into the query so users only put in the last 2 digits of the year and the 4 digit permit number. This will match up with the paper they will get at the desk where Pam is only going to handwrite "14-0050" on the form.

**Comment by racheledelman** [comment]
Great idea! @millzpaugh, can we do both? We can use the input [group addon style](https://getbootstrap.com/css/#forms) to prepend the CU:

![image](https://cloud.githubusercontent.com/assets/2693690/23042673/5c660828-f44e-11e6-948e-0ff67c38c6e3.png)

But if they miss that and start with `CU` or `cu`, we could also accept both of those?
