### ISSUE TITLE
Biz Tracker Design Updates

### ISSUE THREAD

**Issue by racheledelman** [codeforamerica/syracuse_biz_portal#250]

**Comment by millzpaugh** [comment]
[] Add Pam's number if an inspection is denied for business licenses. 
[] add information in the sidebar if the property is found to be in violation during an inspection, a building permit may be required, and the business must be inspected again after the correction is made?

**Comment by racheledelman** [comment]
> Add Pam's number if an inspection is denied for business licenses.

This is in #265

**Comment by millzpaugh** [comment]
this is redundant - i'm going to close it
