### ISSUE TITLE
Business Tracker Content Updates

### ISSUE THREAD

**Issue by racheledelman** [codeforamerica/syracuse_biz_portal#251]

**Comment by millzpaugh** [comment]
1. - [ ] add number to call about permit questions at bottom of results page and on form page 
2. - [ ] Change message to cannot YET lookup amusement/entertainment licenses
3. - [ ] Add text to business license tracker --> if trying to look up the business license number of a business that is not yours submit a FOIA request online through the legal department. if you don't know your business license ID, contact person X
4. - [ ] add link to step page that describes who needs a business license on search page

**Comment by adamewood** [comment]
@racheledelman I see where your questions form yesterday came from now. 

For #3 we need to add text to the CofU tracker input page that says "All businesses that require a business license must post them in a public place. For information about a business' license history, please submit a Freedom of Information Act request." The form is here: http://www.syracuse.ny.us/uploadedFiles/Departments/Law/Content/Freedom%20of%20Information%20Application.pdf Let's talk about how you want to link to it I guess.
