### ISSUE TITLE
Homepage Design Tweaks

### ISSUE THREAD

**Issue by millzpaugh** [codeforamerica/syracuse_biz_portal#252]

**Comment by millzpaugh** [comment]
- [x] Figure out where we want resource matcher on the homepage 
- [ ] Change header photo 
- [ ] Color overlay
- [x] Figure out where we want aggregated checklist to be on homepage
- [ ] Categories and steppages as menu items

**Comment by racheledelman** [comment]
- [x] 1: hero promo
  - Change headline to same gray as body headlines
  - Change bg transparency to 80%
  - Round corners
  - Add same gray outline as cards
- [ ] 2: search
  - If possible, change search button to same style as hero promo buttons
  - If possible, change search input to bootstrap style
  - Add heading with `fa-search`
- [x] 3: resource matcher
  - Add card-style link to resource matcher
- [x] 4: resource matcher
  - change popular pages icon to `fa-bookmark`
  - change why syracuse icon to `fa-home`
- [x] 5: footer
  - add link to checklist (I can't think of a more descriptive name for this...open to suggestions)
  - add link to resource matcher

![homepage v3](https://cloud.githubusercontent.com/assets/2693690/23447401/64281e56-fdff-11e6-9809-9cab95b27d59.png)

I will work on everything else (colors, hero overlay, menu items) later.

**Comment by millzpaugh** [comment]
This looks great, I'll work on it today!
