### ISSUE TITLE
Fix resource matcher search

### ISSUE THREAD

**Issue by millzpaugh** [codeforamerica/syracuse_biz_portal#255]
right now "other" business type doesn't display in searches

**Comment by millzpaugh** [comment]
check-in with @adamewood to see how to revise the search

**Comment by glassresistor** [comment]
ok so as far as I can tell the search is working as desired except in these ways

- "Is a small business needs?" to be added the the forms template.
- Purpose and Industry need to be made optional
- Purpose needs to show Opps w/o purpose on all results and just ones w/o if none are select?  Maybe we should change this.

Form also need to shows its errors.
