### ISSUE TITLE
Error message for returning 0 resources

### ISSUE THREAD

**Issue by adamewood** [codeforamerica/syracuse_biz_portal#275]

**Comment by glassresistor** [comment]
Could you describe this more?

**Comment by adamewood** [comment]
We need an error message for RM when a user doesn't get any results. This is the text I would like to use:

We can't find anything based on your search. Try it again with more resource types, or contact us for more help: (315) 883-2233 or businessdevelopment@syrgov.net.

Let me know if you want a mock
