### ISSUE TITLE
Add logo to header

### ISSUE THREAD

**Issue by racheledelman** [codeforamerica/syracuse_biz_portal#39]
_Note: logo subject to change, if we can find a simpler version/decide the change the color._

Desktop homepage logo, 70px with 2px border that matches header:
![logo-hp-desktop](https://cloud.githubusercontent.com/assets/2693690/20817902/523f88ca-b7df-11e6-8d7e-9f966bdd8526.png)
---

Desktop content page logo, 45px:
![logo-content-desktop](https://cloud.githubusercontent.com/assets/2693690/20817901/521cf012-b7df-11e6-9ae8-c6431f3c51a1.png)
---

Mobile logo (for all pages), 45px:
![logo-mobile](https://cloud.githubusercontent.com/assets/2693690/20817903/524affb6-b7df-11e6-92d1-ad70bcf830ba.png)
---

Logo file:
![syracuselogo](https://cloud.githubusercontent.com/assets/2693690/20818001/d460eb82-b7df-11e6-94e6-15e8420622f6.png)

**Comment by racheledelman** [comment]
Alternatively, we could start all desktop pages off with the big logo, then shrink it to fit in the header on scroll. That would offer more consistency across pages, while solving the problem of the hanging logo blocking content. Thoughts?

**Comment by cweems** [comment]
@racheledelman just diving into this now. I like your second approach of shrinking it on scroll - we share the same nav.html file as a template across everything, so would like to avoid having two versions (although this is possible if we really want to!).

**Comment by racheledelman** [comment]
@cweems Sounds good. Let's shrink.
