### ISSUE TITLE
Redesign panels

### ISSUE THREAD

**Issue by racheledelman** [codeforamerica/syracuse_biz_portal#42]
Redesign panel style (used for resource links and checkbox). New style should be consistent, appropriately sized on desktop and mobile, and more visually simple.

## Current desktop style:
![image](https://cloud.githubusercontent.com/assets/2693690/20853339/1de47a88-b8a0-11e6-9376-1dd7f58b51a7.png)
---

## Current mobile style:
![image](https://cloud.githubusercontent.com/assets/2693690/20853357/3d61b2f4-b8a0-11e6-895d-ccdffed7e5ff.png)

**Comment by cweems** [comment]
@racheledelman Closing this as I think this is what was just merged in!
