### ISSUE TITLE
Add phone number formatting for phone number resource block.

### ISSUE THREAD

**Issue by racheledelman** [codeforamerica/syracuse_biz_portal#43]
Goal: make phone numbers easier to read and use.

When a user adds a phone number to a page via the phone number resource link in Wagtail:

- [x] Add validation to ensure they have entered a ten digit number
- [x] Add error message: "Please enter a full phone number, including area code."
- [x] Add an optional field for extensions
- [ ] Remove or hide `tel:` link on desktop (Up for debate: I think this is confusing and most people won't want to/be able to make calls on desktop, but maybe not?)

Current single field without validation:
![image](https://cloud.githubusercontent.com/assets/2693690/20896649/961361ec-bad3-11e6-8ddb-b629ac1e4b3c.png)

On the front end:
- [x] Display numbers in this format: 555-555-5555 

Current unformatted display:
![image](https://cloud.githubusercontent.com/assets/2693690/20896844/855375b2-bad4-11e6-9e24-ff52cf21ca23.png)

**Comment by cweems** [comment]
Need a field for area code, phone number, and extension.

**Comment by adamewood** [comment]
The current field only allows unformatted numbers
