### ISSUE TITLE
Fields on project for project notebook

### ISSUE THREAD

**Issue by cweems** [codeforamerica/syracuse_biz_portal#59]
Fields currently in LB Bizport. We need to review these to see which we need:

Business License Number
Zip Code
E-Account Number
State Seller's Permit Number
Additional State License Number
Business Structure
DBA Name
Business Type
Number of Employees
Street Address
Business Improvement District (BID)
Square Footage
Number of Parking Spaces

**Comment by adamewood** [comment]
Updated list:
State of New York Certificate of Authority Number
Additional State License Number
Business License Number
Business Structure
DBA Name
Business Type
Number of Employees
Street Address
Tax Address
911 Address
Zip Code
Parcel Number
Business Improvement District (BID)
Square Footage
Number of Parking Spaces

**Comment by cweems** [comment]
Let's plan on making a limited set of 3-5 fields and then expand depending on what is needed.
