### ISSUE TITLE
Client profile view logic for adding a project

### ISSUE THREAD

**Issue by cweems** [codeforamerica/syracuse_biz_portal#62]
Needs more discussion. When used goes to project page there should be a blank project created for them immediately.

**Comment by cweems** [comment]
@racheledelman have you done anything to spec this out?

**Comment by racheledelman** [comment]
Currently I have this list of features. I can work on a wireframe next week. 

- User information section
  - Name
  - Email
  - Change password
- Projects section (can have multiple projects, each with the following subsections)
  - Notebook - information that the user can fill out about their business (**need list of fields**)
  - Checklist - these should be organized by which section of the website they're from, and link back to their step pages. @adamewood, did we decided if we wanted to display all the items, or just the ones that had been completed? I guess the former is more useful. 

Is anything missing?
