### ISSUE TITLE
Implement Search for the site

### ISSUE THREAD

**Issue by mikehern** [codeforamerica/syracuse_biz_portal#79]
Ideally, I'd like to refine Search so that when people type common questions or terms, we can display curated content.  (Think Quora, for small business owners).

Google:
https://developers.google.com/custom-search/docs/promotions

Wagtail:
http://docs.wagtail.io/en/v1.7/reference/contrib/searchpromotions.html#module-wagtail.contrib.wagtailsearchpromotions

**Comment by cweems** [comment]
Google still hasn't crawled our site yet - this may have something to do with the SSL not working.
