### ISSUE TITLE
Category page wireframes

### ISSUE THREAD

**Issue by racheledelman** [codeforamerica/syracuse_biz_portal#86]
This is the intermediary page between the homepage and the step pages. It introduces each category (Learn, Open, and Grow) and lists the steps. Users can navigate via the start/next button, or jump to a specific page.

![category page wireframe](https://cloud.githubusercontent.com/assets/2693690/20985157/18a8fe32-bc78-11e6-9e88-0038d9786390.png)

![category page wireframe - mobile](https://cloud.githubusercontent.com/assets/2693690/20985158/18aa82fc-bc78-11e6-9085-7a8385a69295.png)

The category page is essentially the same as the step pages, with the following changes:

- [x] Use same page title and description as homepage (this may mean that we want to remove the ability to edit these in the CMS, or take other steps to ensure they're the same?)
- [x] Add image to top
- [x] In place of the checklist, add a table of contents listing and linking to each step page in the category
- [x] For mobile, preview the first few items, then hide the rest of the list in an accordion
- [x] Add a "start" button (step pages will have "back" and "next" buttons in this space)

**Comment by cweems** [comment]
This was finished in #90
